// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Diagnostics;
using Foundation;
using iOSDatePickerDialog;
using UIKit;

namespace DatePickerDialogTest
{
    public partial class PresetnedViewController : UIViewController
    {
        public PresetnedViewController(IntPtr handle) : base(handle)
        {
        }

        partial void Show(NSObject sender)
        {
            new DatePickerDialog.Builder()
                                     .SetTitle("My Date")
                               .SetMode(UIDatePickerMode.Date)
                               .SetDefaultDate(DateTime.Now)
                               .SetDateSelected((obj) => Debug.WriteLine(obj.ToString("D")))
                                .Build()
                                .Show();
        }
    }
}
